version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: vigneshchokkalingam-user
          password: $GIFTHUB_Jeevitha@1307.  # context / project UI env-var reference
    steps:
      - checkout 
      - run: lscpu
      
